// Mocks generated by Mockito 5.4.4 from annotations
// in wazly/test/features/wallet/domain/usecases/update_transaction_with_audit_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:wazly/core/errors/failures.dart' as _i5;
import 'package:wazly/features/wallet/domain/entities/account_entity.dart'
    as _i7;
import 'package:wazly/features/wallet/domain/entities/audit_log_entity.dart'
    as _i8;
import 'package:wazly/features/wallet/domain/entities/transaction_entity.dart'
    as _i6;
import 'package:wazly/features/wallet/domain/repositories/wallet_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WalletRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWalletRepository extends _i1.Mock implements _i3.WalletRepository {
  MockWalletRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.TransactionEntity>>>
      getTransactions() => (super.noSuchMethod(
            Invocation.method(
              #getTransactions,
              [],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, List<_i6.TransactionEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.TransactionEntity>>(
              this,
              Invocation.method(
                #getTransactions,
                [],
              ),
            )),
          ) as _i4
              .Future<_i2.Either<_i5.Failure, List<_i6.TransactionEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.TransactionEntity>> getTransactionById(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTransactionById,
          [id],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.TransactionEntity>>.value(
                _FakeEither_0<_i5.Failure, _i6.TransactionEntity>(
          this,
          Invocation.method(
            #getTransactionById,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.TransactionEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> addTransaction(
          _i6.TransactionEntity? transaction) =>
      (super.noSuchMethod(
        Invocation.method(
          #addTransaction,
          [transaction],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #addTransaction,
            [transaction],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> updateTransaction(
          _i6.TransactionEntity? transaction) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTransaction,
          [transaction],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #updateTransaction,
            [transaction],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> updateTransactionWithAudit({
    required _i6.TransactionEntity? oldTransaction,
    required _i6.TransactionEntity? newTransaction,
    required String? reason,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTransactionWithAudit,
          [],
          {
            #oldTransaction: oldTransaction,
            #newTransaction: newTransaction,
            #reason: reason,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #updateTransactionWithAudit,
            [],
            {
              #oldTransaction: oldTransaction,
              #newTransaction: newTransaction,
              #reason: reason,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteTransaction(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteTransaction,
          [id],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #deleteTransaction,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i7.AccountEntity>>> getAccounts() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAccounts,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i7.AccountEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i7.AccountEntity>>(
          this,
          Invocation.method(
            #getAccounts,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i7.AccountEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.AccountEntity>> getAccountById(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAccountById,
          [id],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i7.AccountEntity>>.value(
                _FakeEither_0<_i5.Failure, _i7.AccountEntity>(
          this,
          Invocation.method(
            #getAccountById,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i7.AccountEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> addAccount(
          _i7.AccountEntity? account) =>
      (super.noSuchMethod(
        Invocation.method(
          #addAccount,
          [account],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #addAccount,
            [account],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> updateAccount(
          _i7.AccountEntity? account) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAccount,
          [account],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #updateAccount,
            [account],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteAccount(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAccount,
          [id],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #deleteAccount,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i8.AuditLogEntity>>>
      getAuditLogs() => (super.noSuchMethod(
            Invocation.method(
              #getAuditLogs,
              [],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, List<_i8.AuditLogEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i8.AuditLogEntity>>(
              this,
              Invocation.method(
                #getAuditLogs,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i8.AuditLogEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i8.AuditLogEntity>>>
      getAuditLogsForTransaction(String? transactionId) => (super.noSuchMethod(
            Invocation.method(
              #getAuditLogsForTransaction,
              [transactionId],
            ),
            returnValue: _i4.Future<
                    _i2.Either<_i5.Failure, List<_i8.AuditLogEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i8.AuditLogEntity>>(
              this,
              Invocation.method(
                #getAuditLogsForTransaction,
                [transactionId],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i8.AuditLogEntity>>>);
}
